openapi: 3.0.4
info:
  title: Example Items API
  version: 1.0.0
paths:
  /items:
    get:
      summary: List items
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      type: string
              example:
                data: ["Widget", "Gadget", "Thing"]
