name: OpenAPI Validate

on:
  pull_request:
    paths:
      - 'openapi/**/*.yml'
      - 'openapi/**/*.yaml'
  workflow_dispatch:

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Validate OpenAPI
        uses: char0n/swagger-editor-validate@v1
        with:
          definition-file: openapi/openapi.yaml
          
          
