name: CI Smoke

on:
  pull_request:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: echo "✅ Actions are running for this repo"
